module.exports = {
  apps: [
    {
      name: 'dynamic-pricing-frontend',
      script: 'npm',
      args: 'start',
      cwd: '/opt/rideshare/frontend',
      env: {
        NODE_ENV: 'production',
        PORT: 3000,
        NEXT_PUBLIC_API_URL: 'http://localhost:8000',
        NEXT_PUBLIC_WS_URL: 'ws://localhost:8000',
      },
      instances: 1,
      exec_mode: 'fork',
      autorestart: true,
      watch: false,
      max_memory_restart: '1G',
      error_file: './logs/frontend-error.log',
      out_file: './logs/frontend-out.log',
      log_file: './logs/frontend-combined.log',
      time: true,
    },
    {
      name: 'n8n-workflows',
      script: 'n8n',
      cwd: '/opt/rideshare',
      env: {
        N8N_PORT: 5678,
        N8N_PROTOCOL: 'http',
        N8N_HOST: 'localhost',
        WEBHOOK_URL: 'http://localhost:5678/',
      },
      instances: 1,
      exec_mode: 'fork',
      autorestart: true,
      watch: false,
      max_memory_restart: '512M',
      error_file: './logs/n8n-error.log',
      out_file: './logs/n8n-out.log',
      log_file: './logs/n8n-combined.log',
      time: true,
    },
  ],
};

